{% set build_num = 1 %}
{% set pyston_version = "2.3.1" %}
{% set python_version = "3.8.5" %}
{% set pyston_version2 = ".".join(pyston_version.split(".")[:2]) %}
{% set python_version2 = ".".join(python_version.split(".")[:2]) %}

package:
  name: python
  version: {{ python_version }}
  skip: True  # [not linux]

build:
  number: {{ build_num }}
  string: {{ build_num }}_{{ pyston_version2.replace('.', '') }}_pyston
  #noarch: generic
  track_features:
    - pyston

outputs:
  - name: python
    script: build_base.sh
    version: {{ python_version }}

    run_exports:
      weak:
        - pyston >={{ pyston_version }}
        - python_abi {{ python_version2 }} *_{{ pyston_version2.replace('.', '') }}_pyston
      noarch:
        - {{ pin_subpackage("python", max_pin="x.x", min_pin="x.x") }}

    requirements:
      build:
        - pyston {{ pyston_version }}

      run:
        - pyston {{ pyston_version }}
        - python_abi {{ python_version2 }} *_{{ pyston_version2.replace('.', '') }}_pyston

test:
  commands:
    - python --version | grep Pyston

about:
  home: https://github.com/pyston/pyston
  license: PSF
