{% set build_num = 0 %}
{% set llvm_version = "10.0.1" %}
{% set pyston_version = "2.3.1" %}
{% set python_version = "3.8.12" %}
{% set pyston_version2 = ".".join(pyston_version.split(".")[:2]) %}
{% set python_version2 = ".".join(python_version.split(".")[:2]) %}

package:
  name: pyston{{ pyston_version2 }}
  version: {{ pyston_version }}
  skip: True  # [not linux]

source:
  path: ../../../

build:
  number: {{ build_num }}

  # don't compile python code for now
  skip_compile_pyc:
    "*.py"

  script_env:
    - PYSTON_VERSION2={{ pyston_version2 }}
    - PYTHON_VERSION2={{ python_version2 }}

  always_include_files:
    # this directory is already created by our build requirement on 'python' so will not get bundled automatically
    # but we want the pyston package to create it too so force package our README.txt.
    - lib/python{{ python_version2 }}/site-packages/README.txt

outputs:
  - name: pyston{{ pyston_version2 }}
    script: build_base.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python
        - make
        - cmake
        - virtualenv
        - pkg-config
        - clang={{ llvm_version }}
        - llvmdev={{ llvm_version }}
        - llvm-tools={{ llvm_version }}
        - compiler-rt={{ llvm_version }}
        - libtool
        - sqlite
        - luajit
        - bolt==2.3.1 *_pyston

        - zlib
        - bzip2
        - openssl
        - xz
        - readline
        - ncurses
        - libffi

        # nitrous needs 'nm'
        - binutils 

        # pillow dependencies
        - freetype
        - jpeg
        - libtiff
        - libwebp


      run:
        - zlib
        - bzip2
        - openssl
        - xz
        - readline
        - ncurses
        - libffi
      
      run_constrained:
        python {{ python_version }} *_{{ pyston_version2.replace('.', '') }}_pyston

test:
  commands:
    - pyston -c "print('works')"

about:
  home: https://github.com/pyston/pyston
  license: PSF
  license_file: ../../../LICENSE
  summary: Pyston Python implementation
